### ISSUE TITLE
Nerf the items

### ISSUE THREAD

**Issue by anartoast** [Debonairesnake6/LoLItems#11]
Hello! First i would like to thank you; This mod idea is very good, most of the items idea do work well with risk of rain 2 but there is a huge issue: The numbers are just fucking wild. They do waaaay too much by the first time you got them, won't even mention when stacking.
 I am not the only one that would love to use more this mod but they are way off the curve so please consider nerfing most of them. 
 If you would like to accept new ideas for reworking the effects aswell i will be happy to introduce some of my ideas, that, may be dumb, but are from a real lover of the game and this mod.
Again, good work! I do not code so i would guess it was hella difficult to come with the stuff.

(Also a little issue is: for some reason most of the items won't show the numbers when you stack so i am confused if i should stack them?)

**Comment by Debonairesnake6** [comment]
Do you have some suggestions for what/how much things should be nerfed? I'm always willing to take feedback to try and get the balance right since overall I would like this mod to be power neutral, while also making some items worth getting rather then just turning into scrap. I'm also open to any item reworks or new item implementations if you have those suggestions.

I don't include the total numbers (e.g. bork total on hit damage when stacked) atm, but it's something I can look to add. I just wanted to be careful since if I do it for one thing I would do it for everything, and I think if I have too many numbers on the tool tip it'll be an eye sore if it takes up half the screen lol. I've been trying to get the tool tip updated for the victory/death screens but haven't been able to figure that one out yet.

**Comment by anartoast** [comment]
Yes i would love to argue about it! Thanks for responding 'w'
Some sugestions that i think of the top of my head is nerfing the stats overall;

●  Being able to stack crit damage AND crit is waaay to powerfull on the IE. I'd say that it should give crit only on the first item and only 5% or below crit damage.

● Bannerl is way too powerfull aswell, imagine you have spare drone parts AND cores AND like, 3 mikaels. Maybe it could be a PSG for minions only (not working on turrets)?

● Despite being quite neutral mejai is in a weird spot. I was arguing with someone and we got into a point: stack up to 10% (+1%) damage but lose all the stacks when you fall behind 50% or something like that. A cool sidegrade to watches maybe?

● As i can't see what effects Guinsoo does on the skills (and i can't to math) i would say it is in a weird spot, maybe it is really broken but i would not know.

● Liandry probally is strong aswell as enemies can stack a lot of health on the later stages, maybe a cap that can be raised with further stacking? A really weaker type of poison (Also the icon is weird).

● I think Bork is fine but its weird it not giving any atk speed but maybe i am biased.

● Imperial is very strong with cronobauble but lackluster if you do not have any slow, wich i think it is perfectly fine. Maybe a nerf on the damage to enphase more the stacking as it's a really cheap way to stack damage (crystal needs range, watches needs skill etc, Imperial only needs 1 debuff).

● Rabadons is MASSIVELY powerful, 30% damage is a whole LOT, need a rework ASAP. I can't think of a way to put this item on Ro2, maybe it does not have a place on the game.

● Heartsteel is busted. As a huntress i stacked 32k hp like i was a well plated Cho' Gath. Need a rework. This one i love the idea as i love hp stacking, but i think it should give damage prior to health and/or stack way less health, like, stacking 1 health every 5 kills, still uncapped. Or it could work like league with the damage scaling off health and you get a little bit of health?


 Sorry if i pulled out the "Mucho Texto" i am very excited about this mod as i want to play league but not really want to play league, you know?
For more items, you should get more into cooldown items, maybe void? With the new jungle pets maybe a yellow that can give you a pet wich inherits your items with 20% effectivity or something like that.

**Comment by Debonairesnake6** [comment]
Thanks for the feedback! I haven't had as much time to implement some of these an add more items recently as I've been quite busy. I haven't forgot about wanting to add some of these though. As for your suggestions, I don't agree with all of them, but please correct me if you think I'm still off base with my reasoning.

* I think only giving 5% crit damage would make this item useless. Think of how the math works with laser scope which gives 100% bonus crit damage, and isn't even a great red. Laser scopes gives on average a 50% damage bonus to crits. If I give IR 1/20 of that crit damage my napkin math would indicate it's only a 2.5% damage increase. The number can be tweaked, but Imo only 5% crit damage on stacking is way too low.
* I agree banner is quite powerful. I was trying to make the item not useless on characters that only buy some drones/turrets, but then it makes it way too strong on characters like engi. I don't want to balance around drone parts and empathy cores since you can beat eclipse 8 with only those 2 items anyways.
* I didn't want to make a clone of watches with slightly tweaked numbers. I like how you have to keep killing things to maintain stacks, but an open to changing the numbers on it. 
* Whenever damage is dealt, guinsoos adds 0.1 per stack to the proc coefficient. It doesn't modify items and skills directly so it doesn't show up on ui mods that show that stuff. Hard to gage how strong it is.
* The only time I felt lyandry's was strong was against mythrix, but I also rarely loop. I can look to add a cap similar to poison.
* That's something I struggled with in creating these items. In league items do 5+ things, but in ror they do 1 or 2. Had to balance it without making the stats so minimal when giving too many effects.
* Maybe

**Comment by anartoast** [comment]
Hello! Thanks for responding again, i know "code hard" as i tried toying around on gamemaker sometimes lmao.
First, i am an (surgeon) artist but i have 0 experience with 3D, im more a aspirant illustrator than something. If you think i can help in any way my discord is anartoast. Also you can just rip off the models and animations from the game lmao, team pepega straight does it (Punching a but cause sometimes it looks bad).

 Looking through your points i actually changed my idea around some of the items like the amp damage ones. Despite that, i'd need more time with them to test more;
 
●  Buffing the uptime of Mejai and nerfing the damage a bit can help the item feel more satisfying. I don't really feel much the item unless im commiting genocide, and, if i am commiting genocides, ain't am strong already?

● About the BoRK, i thought of something. ATK speed + healing on every third attack OR it can be a corrupted item:
 Gives 5% ATK speed.1 heal per proc, corrupts syringes and leeching seeds(or schycles). That would make void crit more interesting imo. Atk speed is a really strong thing on this game as almost all animations depends of your atk speed.
 
● If you add a cap to Liandry you can probally balance it around low hp enemies aswell like, adding base damage and nerfing the %. 

● The Deathcap could be a non stackable item or something like that. By the looks 30% looks much, but, as you explained, it does not hit that hard.

● The banner can give like 1 base damage and 10 shield per minion or something that. I can see how hard it is to balance this item in a game you can have like 25 drones to play the game for you.

● Clarifying, the heartsteel only have that much hp cause i was in a loop. Yet, on a normal run i had way too much hp so i would only die if i took like 3 pizzas, pretty much a instawin on moonsoon but i do not play eclipse (skill issue).

● The Mandate idea about amplifying per debuff is really good but it kinda feels like a better deathmark? Maybe it can be a void deathmark, taking care about the "sidegrade" idea.
 
● A good idea to see if guinsoo is strong is making it so affects skills and items directly so you can see the numbers playing. It kinda is a worser luck anyway, no?

Good luck with the stuff you working on, as i said, i am very hyped about this mod and i want to help if i somehow can in any way. I was looking the issue literally everyday lmao (ADHD lore). Sorry if i forgor about something or worded poorly, english aint my native language so i kinda have to load my assets to work on a big text like this.

**Comment by Debonairesnake6** [comment]
Hey again! Sorry it took me so long to respond. I've been quite busy but should have some more free time again in the coming months to start pushing out more frequent updates like when I first started this mod. You mentioned that you may need some more time to do additional testing, if you've done that let me know what your current mindset is around the balance of some of these items based on my previous comment.

- Nerfed mejais damage to 0.5% per stack (max now 12.5% amp from 25%) and duration increased to 10 seconds
- I haven't tried making some corrupted items yet, although I don't think it would be overly difficult. Thematically speaking, BoRK is probably one of the best items to do it with too. I'm assuming from your suggestion you would mean the healing/damage would be removed from the item though right? If so that would feel odd to me because the item in league has the atk spd passive, and the damage on hit and on the third proc. Maybe I just remove the base proc damage and replace it with atk spd? I'm not too sure yet, but I do like your corrupted suggestion for how it could work.
- I think this would be a good direction to take the item. I can use Acrid's poison as a reference. I didn't know that poison deals the higher damage between 1% max hp, and 100% bade damage, plus the damage cap. I won't use these exact numbers, but it would definitely allow for better balance without making it so polarizing.
- I think i'll leave Rabadon's as is for now. It's still only 1.5 ap rounds or watches just without the downsides. May still change this in the future, but I'd need a stronger argument backed up by some math since on paper it looks fine.
- Banner worked in league by buffing your minions, not you, so I would want to stick to that type of item. I can knock this down to 15% for now but open to a rework in the future if there is a better way to balance/implement it.
- Heartsteel bug should be fixed now, although I haven't had too much time to test it. Still have yet to implement the damage amp and sound.
- I think making it void would be quite good, and just a better death mark like you said. I'll look into seeing how I can make this and BoRK void.
- I don't think it is really possible to get those numbers. From my understanding of how it works it's only a true/false for if something will proc. Napkin math: ATG has 10% chance to proc, Skill has 1.5 proc coef, 0.10 X 1.5 = 0.15 or 15% chance to proc. When the function runs you get back a "yes it proc'd" or "no it didn't". You don't get back a "it proc'd because you needed a value greater than 12%" result. So to test the difference in values you'd need to run it again, but can get different results (15% might not proc when 10% does). Maybe I could calculate damage numbers from the extra proc coef to give a rough idea, but I can't get the full scope of the item.

I'm glad you seem to be so passionate about it! For the updates I mentioned in this won't be pushed for a couple days most likely. If I can get the void items working easily I'll include them, otherwise it'll be a future revision.

**Comment by anartoast** [comment]
Ayo! Don't worry about the time you need to change and fix things and stuff. It's ok. I actually forgot to test the mod as i'm not playing ror2 that much anymore but i will be using this mod on my current pack from now on.

● The Mejai do be looking juicy!

● About the BoRK, i meant that it could work like this: passive atk speed and then every third attack it deals damage + flat healing, like 1% health damage + 25 flat damage and 1 flat healing (not cohese numbers i know).

● Bit of a trivia is that the poison cap is rarely used as the health almost is never hit lmao.

● Im dyslexic so maybe another guy could put a phisician argument on the rabbadon.

● I agree with you on the banner.

● I knew it was weird, what even was the bug? Anxious about the CLING ingame.

● Be in mind that (most of) the items need to have some void stacks to work better (not looking at you, polylute and shrimp, ahem) when doing the rework.

● Dang, i would love to see the guinsoo on the hud but maybe this is a thing we can forget, yes.

I'm anxious about the next patch! Wish i had someone to talk with me about the items. My friend's pc won't be running ror2 sadly.
Good luck on the coding stuff. As i said you can ask art (2d) related things and i may help you.

**Comment by Debonairesnake6** [comment]
The new patch went live a couple days ago, so feel free to test any of the changes out.

- I kept the Bork big hit damage the same for the void version. Let me know how you think it feels and I can still modify it if you think it needs further tweaks.
- I know the poison cap is basically never hit, but I found that sometimes having Liandrys made Mythrix kind of trivial so this should make it a little more fair.
- For the Heartsteel bug I have a couple of lists to keep track of everything's base health, and health gained from the item. The list to get the base health is set whenever anything spawns. I accidentally was adding to this list every time, rather than setting it to a specific value which made you health double your every stage when your character spawns in.
- Balance in general is something that I'm going to heavily rely on community feedback for. I don't play this game as much as I used to anymore since I don't really have any friends that play it. Not playing makes it hard to determine how strong something is lol.
- I didn't add the tooltip for guinsoos damage in the previous path but will add it for the next one. It should help indicate how strong the item is, although as previously mentioned not give the full picture.

As a final note, in the previous patch I added the change to have all of those damage tooltips also display on the end game screen. This should make it easier to track how impactful an item is throughout the run, as I often forget to continuously check while I'm playing.

**Comment by Debonairesnake6** [comment]
Scratch the note about adding the tooltip to guinsoos. The function I was going to hook on only includes damage numbers, so I can't reference who dealt the damage in order to record it properly. There is a different way it can be done but I am not currently at the level where I'm able to implement it. I'll put it on my backlog but don't expect it anytime soon.

**Comment by anartoast** [comment]
I do not play that much exactly because of the same reason lmao. We can test together maybe. In the meantime i played like 3 games and made some notes about em (also F to the guinsoo):

● I got mejai on all the 3 games and it looks good, nothing i would constantly feel guilty of using cause of it's weak nor see as scrap, for now.

● Liandrys did not seen much impactful but i played only 1 game with it.

● A recomendation to heartsteel is getting less health from normal enemies, and more health from bosses, mini bosses, and elites. I played a game that i got the item 28 min~ and died (skill issue) 15~ minutes later, stacked 900~ hp, wich is 9 infusions.

**Comment by anartoast** [comment]
Hello! I played a bit more and i can say some things. I don't know where do i post this feedback, if i keep opening this or i post on a sepparate thing. I saw that you posted a discord link for a channel but i can't acess it. Anyway!

**Heartsteel**

The only time i got into killing mithrix was a flurry hunter, getting the item 2 times. On this run, the early game thoughts was all about how op it was feeling, cause when the damage part went on, it was killing everything (runald band + heartsteel). But, as the time went on, it stopped being that relevant. Wich i think it's perfectly fine! Perfect for real! It's a more early game item that do some stuff for you later. Also i love the CLING, everybody does hehe.

**Guinsoo**
I tried stacking a lot this one. Tried stacking with Rex (5) but it wasnt that much effective. A bit with flurry huntress and it was ok.
 No clue on how math works but to this item becomes op, you'd need 100 ish? Maybe that's ok to keep in check but i'm still confused on how to feel about this one.
 
 **Banner**
 Oh boy... This one... It's still OP as hell LMAO.
The problem is not only a banner thing. Damage items like focus crystal, bullet, etc, multiply eachother so they add a lot of damage. No clue on how to balance this one but making it a green should help a little more with the stacking thing.

**BorRK**
It felt almost the same as Heartsteel, nothing much to add.

The other items i did not get much/did not felt much impact in getting.
Still into this mod tho! Good job!

**Comment by Debonairesnake6** [comment]
I'm glad that you're still enjoying the mod! Here are my responses to your comments:

**Heartsteel**
I agree, it's in a fairly balanced state.

**Guinsoo**
I think this item is balanced. I know it doesn't _feel_ that strong, but I think if you can feel it then it is way too strong because it effects almost everything. This more enhances other items and abilities rather than gives direct power. Synergizing with proc chains is where this shines the most, other builds it is much weaker. I think that's okay though, not every item should be super strong otherwise the power creep makes the game too easy.

**Banner**
I still don't think this is that op. The only time you minions can benefit from your other items is with engi. Sure it can be strong on him, but it's basically scrap on everybody else. Unless you are finding some bug or using command to stack 10+ of these I have not found it that impactful in any of my runs.

**Bork**
I agree, it seems balanced.

The purpose of the mod isn't to make the items so powerful you only use them instead of the vanilla items. There are a couple that can be strong, but some should also be weaker than the average vanilla item. While that may not be as exciting to see a new item and not want it, it helps ensure the game stays balanced and doesn't make some items auto win. Some items are auto win with certain combinations in the base game, so I've tried to limit that as much as possible here.

**Thornmail**
I think this would just be a worse razorwire which doesn't seem to exciting. Outside of using gestures with jade elephant I think this would be a completely useless item. Opals only last for a single hit so the 100 armour it gives you really wouldn't help much, and outside of that you have to stack Bucklers which are only 30 a piece.

**Comment by Debonairesnake6** [comment]
FYI I'm going to nerf Banner a bit after playing with it more. I'm keeping the general design, just a number tweak.
