### ISSUE TITLE
visual update for liandry's damage numbers?

### ISSUE THREAD

**Issue by knightmare013** [Debonairesnake6/LoLItems#12]
Could try changing the color of the liandry's burn to blue, just to help distinguish the color from bleed damage to what liandry's is dealing
Also might just look more aesthetically pleasing.

**Comment by Debonairesnake6** [comment]
Hey! Sorry it took me so long to respond. That seems like a great suggestion and I'll include it in the next update. Also, I think I'm going to change the burn icon to be the regular colour rather than blue. Do you still think the bleed damage colour should be blue or would something else be more obvious?

**Comment by Debonairesnake6** [comment]
Here is a picture for what it would look like going forwards. Ignore the damage values as it's on a testing dummy with billions of health.
![image](https://github.com/Debonairesnake6/LoLItems/assets/22126580/4c568478-d1d0-4df4-bd86-a9898ac4a7ae)
