### ISSUE TITLE
Game updated and new DLC is out yippee!

### ISSUE THREAD

**Issue by AndrinoC** [Debonairesnake6/LoLItems#42]
It's been a while but the new big update and DLC are out!
Can we hope on a new update by the next few months?

Btw, love your mod!

**Comment by Debonairesnake6** [comment]
Hey @AndrinoC, good to hear from you again! I'm planning on picking up the DLC shortly and playing around with it a fair bit. If anything is broken because of the DLC I'll be sure to fix it as soon as possible.

In regards to adding new content to my mod, that is something that I'm planning on but it might not be a ton of content. It really depends on how much I'm playing the game again. My goal will be to at least add a few new items to the pool, but I can't make any promises past that.

I'm glad you're still having fun with the mod, it means a lot!

**Comment by AndrinoC** [comment]
As people stated almost any social network, this DLC+Patch is kind of borked. 

Besides the absurd changes to code, awful lot of new bugs, _console code ported to pc?_, and new characters with clunky animations, they kind of messed up the modding tool it seems, most modders will wait until new patches arrive. 

Honestly I believe most of your items will not need any change since the new items are just "paper weight" with no game changing effects that would interact with this mod. 

So, I completely believe that in a couple of weeks or so the game will be stable again and If you feel like it, I could test your mod then and give feedback if I find something broken/lackluster. 

Thanks for your quick response!

**Comment by Debonairesnake6** [comment]
I also saw some comments and videos about how unstable this release is. I tried updating my mod today but couldn't get it working. Once the patches are released and the modding wiki is updated I'll try again to resolve the problems.

**Comment by Debonairesnake6** [comment]
I have the mod mostly updated for the new patch. The API for dots isn't working so I've currently got my hands tied until some other modders fix it.

**Comment by Debonairesnake6** [comment]
Pushed out a new update for the mod, let me know if you experience any bugs with it.
